#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kai Nonaka
# SPDX-License-Identifier: BSD-3-Clause:

import sys
    #2行あけましょう
def tonum(s):
        return int(s)

    #2行あけましょう
ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
